<?php
return array (
    1 => array(
        'bodyId' => '1001',
        'faceId' => '2001',
        'budId' => '3001',
        'dressId' => '4001',
        'gardenCount' => '1',
        'mapCount' => '1',
    ),
    2 => array(
        'bodyId' => '1004',
        'faceId' => '2004',
        'budId' => '3004',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    3 => array(
        'bodyId' => '1005',
        'faceId' => '0',
        'budId' => '0',
        'dressId' => '4004',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    4 => array(
        'bodyId' => '1006',
        'faceId' => '0',
        'budId' => '3005',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    5 => array(
        'bodyId' => '1007',
        'faceId' => '2005',
        'budId' => '0',
        'dressId' => '4005',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    6 => array(
        'bodyId' => '1008',
        'faceId' => '0',
        'budId' => '0',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    7 => array(
        'bodyId' => '0',
        'faceId' => '0',
        'budId' => '3006',
        'dressId' => '0',
        'gardenCount' => '2',
        'mapCount' => '0',
    ),
    8 => array(
        'bodyId' => '0',
        'faceId' => '2006',
        'budId' => '0',
        'dressId' => '4006',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    9 => array(
        'bodyId' => '1009',
        'faceId' => '0',
        'budId' => '0',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    10 => array(
        'bodyId' => '0',
        'faceId' => '0',
        'budId' => '3007',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    11 => array(
        'bodyId' => '0',
        'faceId' => '0',
        'budId' => '0',
        'dressId' => '4007',
        'gardenCount' => '0',
        'mapCount' => '2',
    ),
    12 => array(
        'bodyId' => '1010',
        'faceId' => '2007',
        'budId' => '0',
        'dressId' => '0',
        'gardenCount' => '3',
        'mapCount' => '0',
    ),
    13 => array(
        'bodyId' => '0',
        'faceId' => '0',
        'budId' => '3008',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    14 => array(
        'bodyId' => '0',
        'faceId' => '0',
        'budId' => '0',
        'dressId' => '4008',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    15 => array(
        'bodyId' => '1011',
        'faceId' => '0',
        'budId' => '0',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    16 => array(
        'bodyId' => '0',
        'faceId' => '2008',
        'budId' => '3009',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    17 => array(
        'bodyId' => '0',
        'faceId' => '0',
        'budId' => '0',
        'dressId' => '4009',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    18 => array(
        'bodyId' => '1012',
        'faceId' => '0',
        'budId' => '0',
        'dressId' => '0',
        'gardenCount' => '4',
        'mapCount' => '0',
    ),
    19 => array(
        'bodyId' => '0',
        'faceId' => '0',
        'budId' => '3010',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    20 => array(
        'bodyId' => '0',
        'faceId' => '2009',
        'budId' => '0',
        'dressId' => '4010',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    21 => array(
        'bodyId' => '1013',
        'faceId' => '0',
        'budId' => '0',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '3',
    ),
    22 => array(
        'bodyId' => '0',
        'faceId' => '0',
        'budId' => '3011',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    23 => array(
        'bodyId' => '0',
        'faceId' => '0',
        'budId' => '0',
        'dressId' => '4011',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    24 => array(
        'bodyId' => '1014',
        'faceId' => '2010',
        'budId' => '0',
        'dressId' => '0',
        'gardenCount' => '5',
        'mapCount' => '0',
    ),
    25 => array(
        'bodyId' => '0',
        'faceId' => '0',
        'budId' => '3012',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    26 => array(
        'bodyId' => '0',
        'faceId' => '0',
        'budId' => '0',
        'dressId' => '4012',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    27 => array(
        'bodyId' => '1015',
        'faceId' => '0',
        'budId' => '0',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    28 => array(
        'bodyId' => '0',
        'faceId' => '2011',
        'budId' => '3013',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    29 => array(
        'bodyId' => '0',
        'faceId' => '0',
        'budId' => '0',
        'dressId' => '4013',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    30 => array(
        'bodyId' => '1016',
        'faceId' => '0',
        'budId' => '0',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    31 => array(
        'bodyId' => '0',
        'faceId' => '0',
        'budId' => '3014',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    32 => array(
        'bodyId' => '0',
        'faceId' => '2012',
        'budId' => '0',
        'dressId' => '4014',
        'gardenCount' => '6',
        'mapCount' => '0',
    ),
    33 => array(
        'bodyId' => '1017',
        'faceId' => '0',
        'budId' => '0',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    34 => array(
        'bodyId' => '0',
        'faceId' => '0',
        'budId' => '3015',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    35 => array(
        'bodyId' => '0',
        'faceId' => '0',
        'budId' => '0',
        'dressId' => '4015',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    36 => array(
        'bodyId' => '1018',
        'faceId' => '2013',
        'budId' => '0',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '4',
    ),
    37 => array(
        'bodyId' => '0',
        'faceId' => '0',
        'budId' => '3016',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    38 => array(
        'bodyId' => '0',
        'faceId' => '0',
        'budId' => '0',
        'dressId' => '4016',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    39 => array(
        'bodyId' => '1019',
        'faceId' => '0',
        'budId' => '0',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    40 => array(
        'bodyId' => '0',
        'faceId' => '2014',
        'budId' => '3017',
        'dressId' => '0',
        'gardenCount' => '7',
        'mapCount' => '0',
    ),
    41 => array(
        'bodyId' => '0',
        'faceId' => '0',
        'budId' => '0',
        'dressId' => '4017',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    42 => array(
        'bodyId' => '1020',
        'faceId' => '0',
        'budId' => '0',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    43 => array(
        'bodyId' => '0',
        'faceId' => '0',
        'budId' => '3018',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    44 => array(
        'bodyId' => '0',
        'faceId' => '2015',
        'budId' => '0',
        'dressId' => '4018',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    45 => array(
        'bodyId' => '1021',
        'faceId' => '0',
        'budId' => '0',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    46 => array(
        'bodyId' => '0',
        'faceId' => '0',
        'budId' => '3019',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    47 => array(
        'bodyId' => '0',
        'faceId' => '0',
        'budId' => '0',
        'dressId' => '4019',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    48 => array(
        'bodyId' => '1022',
        'faceId' => '2016',
        'budId' => '0',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    49 => array(
        'bodyId' => '0',
        'faceId' => '0',
        'budId' => '3020',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    50 => array(
        'bodyId' => '0',
        'faceId' => '0',
        'budId' => '0',
        'dressId' => '4020',
        'gardenCount' => '8',
        'mapCount' => '0',
    ),
    51 => array(
        'bodyId' => '1023',
        'faceId' => '0',
        'budId' => '0',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '5',
    ),
    52 => array(
        'bodyId' => '0',
        'faceId' => '2017',
        'budId' => '3021',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    53 => array(
        'bodyId' => '0',
        'faceId' => '0',
        'budId' => '0',
        'dressId' => '4021',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    54 => array(
        'bodyId' => '1024',
        'faceId' => '0',
        'budId' => '0',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    55 => array(
        'bodyId' => '0',
        'faceId' => '0',
        'budId' => '3022',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    56 => array(
        'bodyId' => '0',
        'faceId' => '2018',
        'budId' => '0',
        'dressId' => '4022',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    57 => array(
        'bodyId' => '1025',
        'faceId' => '0',
        'budId' => '0',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    58 => array(
        'bodyId' => '0',
        'faceId' => '0',
        'budId' => '3023',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    59 => array(
        'bodyId' => '0',
        'faceId' => '0',
        'budId' => '0',
        'dressId' => '4023',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    60 => array(
        'bodyId' => '0',
        'faceId' => '2019',
        'budId' => '0',
        'dressId' => '0',
        'gardenCount' => '9',
        'mapCount' => '0',
    ),
    61 => array(
        'bodyId' => '1026',
        'faceId' => '0',
        'budId' => '0',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    62 => array(
        'bodyId' => '0',
        'faceId' => '0',
        'budId' => '3024',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    63 => array(
        'bodyId' => '0',
        'faceId' => '0',
        'budId' => '0',
        'dressId' => '4024',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    64 => array(
        'bodyId' => '0',
        'faceId' => '2020',
        'budId' => '0',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    65 => array(
        'bodyId' => '1027',
        'faceId' => '0',
        'budId' => '0',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    66 => array(
        'bodyId' => '0',
        'faceId' => '0',
        'budId' => '3025',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    67 => array(
        'bodyId' => '0',
        'faceId' => '0',
        'budId' => '0',
        'dressId' => '4025',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    68 => array(
        'bodyId' => '0',
        'faceId' => '2021',
        'budId' => '0',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    69 => array(
        'bodyId' => '1028',
        'faceId' => '0',
        'budId' => '0',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    70 => array(
        'bodyId' => '0',
        'faceId' => '0',
        'budId' => '3026',
        'dressId' => '0',
        'gardenCount' => '10',
        'mapCount' => '0',
    ),
    71 => array(
        'bodyId' => '0',
        'faceId' => '0',
        'budId' => '0',
        'dressId' => '4026',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    72 => array(
        'bodyId' => '0',
        'faceId' => '2022',
        'budId' => '0',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    73 => array(
        'bodyId' => '1029',
        'faceId' => '0',
        'budId' => '0',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    74 => array(
        'bodyId' => '0',
        'faceId' => '0',
        'budId' => '3027',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    75 => array(
        'bodyId' => '0',
        'faceId' => '0',
        'budId' => '0',
        'dressId' => '4027',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    76 => array(
        'bodyId' => '0',
        'faceId' => '2023',
        'budId' => '0',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    77 => array(
        'bodyId' => '1030',
        'faceId' => '0',
        'budId' => '0',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    78 => array(
        'bodyId' => '0',
        'faceId' => '0',
        'budId' => '3028',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    79 => array(
        'bodyId' => '0',
        'faceId' => '0',
        'budId' => '0',
        'dressId' => '4028',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    80 => array(
        'bodyId' => '0',
        'faceId' => '2024',
        'budId' => '0',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    81 => array(
        'bodyId' => '0',
        'faceId' => '0',
        'budId' => '0',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    82 => array(
        'bodyId' => '0',
        'faceId' => '0',
        'budId' => '3029',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    83 => array(
        'bodyId' => '0',
        'faceId' => '0',
        'budId' => '0',
        'dressId' => '4029',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    84 => array(
        'bodyId' => '0',
        'faceId' => '2025',
        'budId' => '0',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    85 => array(
        'bodyId' => '0',
        'faceId' => '0',
        'budId' => '0',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    86 => array(
        'bodyId' => '0',
        'faceId' => '0',
        'budId' => '3030',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    87 => array(
        'bodyId' => '0',
        'faceId' => '0',
        'budId' => '0',
        'dressId' => '4030',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),
    0 => array(
        'bodyId' => '0',
        'faceId' => '0',
        'budId' => '0',
        'dressId' => '0',
        'gardenCount' => '0',
        'mapCount' => '0',
    ),

);
