<?php

return array(
	1 => array(
		'name' => Yii::t('Item', 'itemName_1'),
		'canBuy' => '1',
		'canSell' => '1',
		'image' => 'n_item_r006.png',
		'category' => '1',
		'level' => '1',
		'description' => Yii::t('Item', 'itemDecription_1'),
		'useLevel' => '0',
		'canUse' => '1',
		'bindRule' => '2',
		'price' => '100',
		'sellPrice' => '1',
		'moneyType' => '0',
		'type' => '1',
		'effect' => array('attributes'=>array(1=>250,),),
		),
	2 => array(
		'name' => Yii::t('Item', 'itemName_2'),
		'canBuy' => '1',
		'canSell' => '1',
		'image' => 'n_item_r009.png',
		'category' => '1',
		'level' => '2',
		'description' => Yii::t('Item', 'itemDecription_2'),
		'useLevel' => '0',
		'canUse' => '1',
		'bindRule' => '2',
		'price' => '500',
		'sellPrice' => '5',
		'moneyType' => '0',
		'type' => '1',
		'effect' => array('attributes'=>array(1=>1000,),),
		),
	3 => array(
		'name' => Yii::t('Item', 'itemName_3'),
		'canBuy' => '1',
		'canSell' => '1',
		'image' => 'n_item_r010.png',
		'category' => '1',
		'level' => '3',
		'description' => Yii::t('Item', 'itemDecription_3'),
		'useLevel' => '0',
		'canUse' => '1',
		'bindRule' => '2',
		'price' => '1500',
		'sellPrice' => '15',
		'moneyType' => '0',
		'type' => '1',
		'effect' => array('attributes'=>array(1=>2500,),),
		),
	4 => array(
		'name' => Yii::t('Item', 'itemName_4'),
		'canBuy' => '1',
		'canSell' => '1',
		'image' => 'n_item_r007.png',
		'category' => '1',
		'level' => '4',
		'description' => Yii::t('Item', 'itemDecription_4'),
		'useLevel' => '0',
		'canUse' => '1',
		'bindRule' => '2',
		'price' => '5000',
		'sellPrice' => '50',
		'moneyType' => '0',
		'type' => '1',
		'effect' => array('attributes'=>array(1=>3500,),),
		),
	5 => array(
		'name' => Yii::t('Item', 'itemName_5'),
		'canBuy' => '1',
		'canSell' => '1',
		'image' => 'n_item_r008.png',
		'category' => '1',
		'level' => '5',
		'description' => Yii::t('Item', 'itemDecription_5'),
		'useLevel' => '0',
		'canUse' => '1',
		'bindRule' => '2',
		'price' => '20000',
		'sellPrice' => '100',
		'moneyType' => '0',
		'type' => '1',
		'effect' => array('attributes'=>array(1=>5500,),),
		),
	6 => array(
		'name' => Yii::t('Item', 'itemName_6'),
		'canBuy' => '1',
		'canSell' => '1',
		'image' => 'n_item_r022.png',
		'category' => '1',
		'level' => '1',
		'description' => Yii::t('Item', 'itemDecription_6'),
		'useLevel' => '0',
		'canUse' => '1',
		'bindRule' => '2',
		'price' => '100',
		'sellPrice' => '1',
		'moneyType' => '0',
		'type' => '2',
		'effect' => array('attributes'=>array(2=>250,),),
		),
	7 => array(
		'name' => Yii::t('Item', 'itemName_7'),
		'canBuy' => '1',
		'canSell' => '1',
		'image' => 'n_item_r021.png',
		'category' => '1',
		'level' => '2',
		'description' => Yii::t('Item', 'itemDecription_7'),
		'useLevel' => '0',
		'canUse' => '1',
		'bindRule' => '2',
		'price' => '500',
		'sellPrice' => '5',
		'moneyType' => '0',
		'type' => '2',
		'effect' => array('attributes'=>array(2=>1000,),),
		),
	8 => array(
		'name' => Yii::t('Item', 'itemName_8'),
		'canBuy' => '1',
		'canSell' => '1',
		'image' => 'n_item_r023.png',
		'category' => '1',
		'level' => '3',
		'description' => Yii::t('Item', 'itemDecription_8'),
		'useLevel' => '0',
		'canUse' => '1',
		'bindRule' => '2',
		'price' => '1500',
		'sellPrice' => '15',
		'moneyType' => '0',
		'type' => '2',
		'effect' => array('attributes'=>array(2=>2500,),),
		),
	9 => array(
		'name' => Yii::t('Item', 'itemName_9'),
		'canBuy' => '1',
		'canSell' => '1',
		'image' => 'n_item_r024.png',
		'category' => '1',
		'level' => '4',
		'description' => Yii::t('Item', 'itemDecription_9'),
		'useLevel' => '0',
		'canUse' => '1',
		'bindRule' => '2',
		'price' => '5000',
		'sellPrice' => '50',
		'moneyType' => '0',
		'type' => '2',
		'effect' => array('attributes'=>array(2=>3500,),),
		),
	10 => array(
		'name' => Yii::t('Item', 'itemName_10'),
		'canBuy' => '1',
		'canSell' => '1',
		'image' => 'n_item_r025.png',
		'category' => '1',
		'level' => '5',
		'description' => Yii::t('Item', 'itemDecription_10'),
		'useLevel' => '0',
		'canUse' => '1',
		'bindRule' => '2',
		'price' => '20000',
		'sellPrice' => '100',
		'moneyType' => '0',
		'type' => '2',
		'effect' => array('attributes'=>array(2=>5500,),),
		),
	11 => array(
		'name' => Yii::t('Item', 'itemName_11'),
		'canBuy' => '1',
		'canSell' => '1',
		'image' => 'n_item_r005.png',
		'category' => '1',
		'level' => '1',
		'description' => Yii::t('Item', 'itemDecription_11'),
		'useLevel' => '0',
		'canUse' => '1',
		'bindRule' => '2',
		'price' => '100',
		'sellPrice' => '1',
		'moneyType' => '0',
		'type' => '3',
		'effect' => array('attributes'=>array(3=>250,),),
		),
	12 => array(
		'name' => Yii::t('Item', 'itemName_12'),
		'canBuy' => '1',
		'canSell' => '1',
		'image' => 'n_item_r002.png',
		'category' => '1',
		'level' => '2',
		'description' => Yii::t('Item', 'itemDecription_12'),
		'useLevel' => '0',
		'canUse' => '1',
		'bindRule' => '2',
		'price' => '500',
		'sellPrice' => '5',
		'moneyType' => '0',
		'type' => '3',
		'effect' => array('attributes'=>array(3=>1000,),),
		),
	13 => array(
		'name' => Yii::t('Item', 'itemName_13'),
		'canBuy' => '1',
		'canSell' => '1',
		'image' => 'n_item_r003.png',
		'category' => '1',
		'level' => '3',
		'description' => Yii::t('Item', 'itemDecription_13'),
		'useLevel' => '0',
		'canUse' => '1',
		'bindRule' => '2',
		'price' => '1500',
		'sellPrice' => '15',
		'moneyType' => '0',
		'type' => '3',
		'effect' => array('attributes'=>array(3=>2500,),),
		),
	14 => array(
		'name' => Yii::t('Item', 'itemName_14'),
		'canBuy' => '1',
		'canSell' => '1',
		'image' => 'n_item_r004.png',
		'category' => '1',
		'level' => '4',
		'description' => Yii::t('Item', 'itemDecription_14'),
		'useLevel' => '0',
		'canUse' => '1',
		'bindRule' => '2',
		'price' => '5000',
		'sellPrice' => '50',
		'moneyType' => '0',
		'type' => '3',
		'effect' => array('attributes'=>array(3=>3500,),),
		),
	15 => array(
		'name' => Yii::t('Item', 'itemName_15'),
		'canBuy' => '1',
		'canSell' => '1',
		'image' => 'n_item_r001.png',
		'category' => '1',
		'level' => '5',
		'description' => Yii::t('Item', 'itemDecription_15'),
		'useLevel' => '0',
		'canUse' => '1',
		'bindRule' => '2',
		'price' => '20000',
		'sellPrice' => '100',
		'moneyType' => '0',
		'type' => '3',
		'effect' => array('attributes'=>array(3=>5500,),),
		),
	16 => array(
		'name' => Yii::t('Item', 'itemName_16'),
		'canBuy' => '1',
		'canSell' => '1',
		'image' => 'n_item_r029.png',
		'category' => '1',
		'level' => '1',
		'description' => Yii::t('Item', 'itemDecription_16'),
		'useLevel' => '0',
		'canUse' => '1',
		'bindRule' => '2',
		'price' => '100',
		'sellPrice' => '1',
		'moneyType' => '0',
		'type' => '4',
		'effect' => array('attributes'=>array(4=>250,),),
		),
	17 => array(
		'name' => Yii::t('Item', 'itemName_17'),
		'canBuy' => '1',
		'canSell' => '1',
		'image' => 'n_item_r026.png',
		'category' => '1',
		'level' => '2',
		'description' => Yii::t('Item', 'itemDecription_17'),
		'useLevel' => '0',
		'canUse' => '1',
		'bindRule' => '2',
		'price' => '500',
		'sellPrice' => '5',
		'moneyType' => '0',
		'type' => '4',
		'effect' => array('attributes'=>array(4=>1000,),),
		),
	18 => array(
		'name' => Yii::t('Item', 'itemName_18'),
		'canBuy' => '1',
		'canSell' => '1',
		'image' => 'n_item_r027.png',
		'category' => '1',
		'level' => '3',
		'description' => Yii::t('Item', 'itemDecription_18'),
		'useLevel' => '0',
		'canUse' => '1',
		'bindRule' => '2',
		'price' => '1500',
		'sellPrice' => '15',
		'moneyType' => '0',
		'type' => '4',
		'effect' => array('attributes'=>array(4=>2500,),),
		),
	19 => array(
		'name' => Yii::t('Item', 'itemName_19'),
		'canBuy' => '1',
		'canSell' => '1',
		'image' => 'n_item_r028.png',
		'category' => '1',
		'level' => '4',
		'description' => Yii::t('Item', 'itemDecription_19'),
		'useLevel' => '0',
		'canUse' => '1',
		'bindRule' => '2',
		'price' => '5000',
		'sellPrice' => '50',
		'moneyType' => '0',
		'type' => '4',
		'effect' => array('attributes'=>array(4=>3500,),),
		),
	20 => array(
		'name' => Yii::t('Item', 'itemName_20'),
		'canBuy' => '1',
		'canSell' => '1',
		'image' => 'n_item_r030.png',
		'category' => '1',
		'level' => '5',
		'description' => Yii::t('Item', 'itemDecription_20'),
		'useLevel' => '0',
		'canUse' => '1',
		'bindRule' => '2',
		'price' => '20000',
		'sellPrice' => '100',
		'moneyType' => '0',
		'type' => '4',
		'effect' => array('attributes'=>array(4=>5500,),),
		),
	21 => array(
		'name' => Yii::t('Item', 'itemName_21'),
		'canBuy' => '1',
		'canSell' => '1',
		'image' => 'n_item_r011.png',
		'category' => '1',
		'level' => '1',
		'description' => Yii::t('Item', 'itemDecription_21'),
		'useLevel' => '0',
		'canUse' => '1',
		'bindRule' => '2',
		'price' => '150',
		'sellPrice' => '1',
		'moneyType' => '0',
		'type' => '5',
		'effect' => array('attributes'=>array(5=>250,),),
		),
	22 => array(
		'name' => Yii::t('Item', 'itemName_22'),
		'canBuy' => '1',
		'canSell' => '1',
		'image' => 'n_item_r015.png',
		'category' => '1',
		'level' => '2',
		'description' => Yii::t('Item', 'itemDecription_22'),
		'useLevel' => '0',
		'canUse' => '1',
		'bindRule' => '2',
		'price' => '750',
		'sellPrice' => '5',
		'moneyType' => '0',
		'type' => '5',
		'effect' => array('attributes'=>array(5=>1000,),),
		),
	23 => array(
		'name' => Yii::t('Item', 'itemName_23'),
		'canBuy' => '1',
		'canSell' => '1',
		'image' => 'n_item_r014.png',
		'category' => '1',
		'level' => '3',
		'description' => Yii::t('Item', 'itemDecription_23'),
		'useLevel' => '0',
		'canUse' => '1',
		'bindRule' => '2',
		'price' => '2250',
		'sellPrice' => '15',
		'moneyType' => '0',
		'type' => '5',
		'effect' => array('attributes'=>array(5=>2500,),),
		),
	24 => array(
		'name' => Yii::t('Item', 'itemName_24'),
		'canBuy' => '1',
		'canSell' => '1',
		'image' => 'n_item_r012.png',
		'category' => '1',
		'level' => '4',
		'description' => Yii::t('Item', 'itemDecription_24'),
		'useLevel' => '0',
		'canUse' => '1',
		'bindRule' => '2',
		'price' => '7500',
		'sellPrice' => '50',
		'moneyType' => '0',
		'type' => '5',
		'effect' => array('attributes'=>array(5=>3500,),),
		),
	25 => array(
		'name' => Yii::t('Item', 'itemName_25'),
		'canBuy' => '1',
		'canSell' => '1',
		'image' => 'n_item_r013.png',
		'category' => '1',
		'level' => '5',
		'description' => Yii::t('Item', 'itemDecription_25'),
		'useLevel' => '0',
		'canUse' => '1',
		'bindRule' => '2',
		'price' => '30000',
		'sellPrice' => '100',
		'moneyType' => '0',
		'type' => '5',
		'effect' => array('attributes'=>array(5=>5500,),),
		),
	26 => array(
		'name' => Yii::t('Item', 'itemName_26'),
		'canBuy' => '1',
		'canSell' => '1',
		'image' => 'n_item_r017.png',
		'category' => '1',
		'level' => '1',
		'description' => Yii::t('Item', 'itemDecription_26'),
		'useLevel' => '0',
		'canUse' => '1',
		'bindRule' => '2',
		'price' => '200',
		'sellPrice' => '1',
		'moneyType' => '0',
		'type' => '6',
		'effect' => array('attributes'=>array(6=>250,),),
		),
	27 => array(
		'name' => Yii::t('Item', 'itemName_27'),
		'canBuy' => '1',
		'canSell' => '1',
		'image' => 'n_item_r020.png',
		'category' => '1',
		'level' => '2',
		'description' => Yii::t('Item', 'itemDecription_27'),
		'useLevel' => '0',
		'canUse' => '1',
		'bindRule' => '2',
		'price' => '1000',
		'sellPrice' => '5',
		'moneyType' => '0',
		'type' => '6',
		'effect' => array('attributes'=>array(6=>1000,),),
		),
	28 => array(
		'name' => Yii::t('Item', 'itemName_28'),
		'canBuy' => '1',
		'canSell' => '1',
		'image' => 'n_item_r019.png',
		'category' => '1',
		'level' => '3',
		'description' => Yii::t('Item', 'itemDecription_28'),
		'useLevel' => '0',
		'canUse' => '1',
		'bindRule' => '2',
		'price' => '3000',
		'sellPrice' => '15',
		'moneyType' => '0',
		'type' => '6',
		'effect' => array('attributes'=>array(6=>2500,),),
		),
	29 => array(
		'name' => Yii::t('Item', 'itemName_29'),
		'canBuy' => '1',
		'canSell' => '1',
		'image' => 'n_item_r018.png',
		'category' => '1',
		'level' => '4',
		'description' => Yii::t('Item', 'itemDecription_29'),
		'useLevel' => '0',
		'canUse' => '1',
		'bindRule' => '2',
		'price' => '10000',
		'sellPrice' => '50',
		'moneyType' => '0',
		'type' => '6',
		'effect' => array('attributes'=>array(6=>3500,),),
		),
	30 => array(
		'name' => Yii::t('Item', 'itemName_30'),
		'canBuy' => '1',
		'canSell' => '1',
		'image' => 'n_item_r016.png',
		'category' => '1',
		'level' => '5',
		'description' => Yii::t('Item', 'itemDecription_30'),
		'useLevel' => '0',
		'canUse' => '1',
		'bindRule' => '2',
		'price' => '40000',
		'sellPrice' => '100',
		'moneyType' => '0',
		'type' => '6',
		'effect' => array('attributes'=>array(6=>5500,),),
		),
	);
?>