<?php

return array(
    1 => array('id' => '1', 'type' => 'resItem', 'num' => 1),
    2 => array('id' => '2', 'type' => 'resItem', 'num' => 1),
    3 => array('id' => '3', 'type' => 'resItem', 'num' => 1),
    4 => array('id' => '4', 'type' => 'resItem', 'num' => 1),
    5 => array('id' => '5', 'type' => 'resItem', 'num' => 1),
    6 => array('id' => '6', 'type' => 'resItem', 'num' => 1),
    7 => array('id' => '7', 'type' => 'resItem', 'num' => 1),
    8 => array('id' => '8', 'type' => 'resItem', 'num' => 1),
    9 => array('id' => '9', 'type' => 'resItem', 'num' => 1),
    10 => array('id' => '10', 'type' => 'resItem', 'num' => 1),
    11 => array('id' => '11', 'type' => 'resItem', 'num' => 1),
    12 => array('id' => '12', 'type' => 'resItem', 'num' => 1),
    13 => array('id' => '13', 'type' => 'resItem', 'num' => 1),
    14 => array('id' => '14', 'type' => 'resItem', 'num' => 1),
    15 => array('id' => '15', 'type' => 'resItem', 'num' => 1),
    16 => array('id' => '16', 'type' => 'resItem', 'num' => 1),
    17 => array('id' => '17', 'type' => 'resItem', 'num' => 1),
    18 => array('id' => '18', 'type' => 'resItem', 'num' => 1),
    19 => array('id' => '19', 'type' => 'resItem', 'num' => 1),
    20 => array('id' => '20', 'type' => 'resItem', 'num' => 1),
    21 => array('id' => '21', 'type' => 'resItem', 'num' => 1),
    22 => array('id' => '22', 'type' => 'resItem', 'num' => 1),
    23 => array('id' => '23', 'type' => 'resItem', 'num' => 1),
    24 => array('id' => '24', 'type' => 'resItem', 'num' => 1),
    25 => array('id' => '25', 'type' => 'resItem', 'num' => 1),
    26 => array('id' => '26', 'type' => 'resItem', 'num' => 1),
    27 => array('id' => '27', 'type' => 'resItem', 'num' => 1),
    28 => array('id' => '28', 'type' => 'resItem', 'num' => 1),
    29 => array('id' => '29', 'type' => 'resItem', 'num' => 1),
    30 => array('id' => '30', 'type' => 'resItem', 'num' => 1),
    101 => array('id' => '10000', 'type' => 'gold', 'rand' => array(5, 15)),
    102 => array('id' => '20000', 'type' => 'seed', 'num' => 1),
    103 => array('id' => '10000', 'type' => 'gold', 'levelGold' => 100),
    104 => array('id' => '10001', 'type' => 'money', 'money' => 100),
    105 => array('id' => '10001', 'type' => 'money', 'money' => 1000),
    106 => array('id' => '10001', 'type' => 'money', 'money' => 2000),
);
?>