<?php
return array(
    1001 => array(
        'dataName' => 'n_seed_b001',
        'image' => '1001',
        'dataType' => '1',
        'level' => '1',
        'unlockLevel' => '1',
        'growValue' => '20',
    ),
    1002 => array(
        'dataName' => 'n_seed_b007',
        'image' => '1002',
        'dataType' => '1',
        'level' => '2',
        'unlockLevel' => '1',
        'growValue' => '20',
    ),
    1003 => array(
        'dataName' => 'n_seed_b002',
        'image' => '1003',
        'dataType' => '1',
        'level' => '3',
        'unlockLevel' => '1',
        'growValue' => '20',
    ),
    1004 => array(
        'dataName' => 'n_seed_b003',
        'image' => '1004',
        'dataType' => '1',
        'level' => '4',
        'unlockLevel' => '2',
        'growValue' => '56',
    ),
    1005 => array(
        'dataName' => 'n_seed_b004',
        'image' => '1005',
        'dataType' => '1',
        'level' => '5',
        'unlockLevel' => '3',
        'growValue' => '103',
    ),
    1006 => array(
        'dataName' => 'n_seed_b005',
        'image' => '1006',
        'dataType' => '1',
        'level' => '6',
        'unlockLevel' => '4',
        'growValue' => '160',
    ),
    1007 => array(
        'dataName' => 'n_seed_b006',
        'image' => '1007',
        'dataType' => '1',
        'level' => '7',
        'unlockLevel' => '5',
        'growValue' => '223',
    ),
    1008 => array(
        'dataName' => 'n_seed_b008',
        'image' => '1008',
        'dataType' => '1',
        'level' => '8',
        'unlockLevel' => '6',
        'growValue' => '193',
    ),
    1009 => array(
        'dataName' => 'n_seed_b009',
        'image' => '1009',
        'dataType' => '1',
        'level' => '9',
        'unlockLevel' => '9',
        'growValue' => '540',
    ),
    1010 => array(
        'dataName' => 'n_seed_b010',
        'image' => '1010',
        'dataType' => '1',
        'level' => '10',
        'unlockLevel' => '12',
        'growValue' => '831',
    ),
    1011 => array(
        'dataName' => 'n_seed_b011',
        'image' => '1011',
        'dataType' => '1',
        'level' => '11',
        'unlockLevel' => '15',
        'growValue' => '1161',
    ),
    1012 => array(
        'dataName' => 'n_seed_b012',
        'image' => '1012',
        'dataType' => '1',
        'level' => '12',
        'unlockLevel' => '18',
        'growValue' => '1527',
    ),
    1013 => array(
        'dataName' => 'n_seed_b013',
        'image' => '1013',
        'dataType' => '1',
        'level' => '13',
        'unlockLevel' => '21',
        'growValue' => '1924',
    ),
    1014 => array(
        'dataName' => 'n_seed_b014',
        'image' => '1014',
        'dataType' => '1',
        'level' => '14',
        'unlockLevel' => '24',
        'growValue' => '2351',
    ),
    1015 => array(
        'dataName' => 'n_seed_b015',
        'image' => '1015',
        'dataType' => '1',
        'level' => '15',
        'unlockLevel' => '27',
        'growValue' => '2805',
    ),
    1016 => array(
        'dataName' => 'n_seed_b016',
        'image' => '1016',
        'dataType' => '1',
        'level' => '16',
        'unlockLevel' => '30',
        'growValue' => '3286',
    ),
    1017 => array(
        'dataName' => 'n_seed_b017',
        'image' => '1017',
        'dataType' => '1',
        'level' => '17',
        'unlockLevel' => '33',
        'growValue' => '3791',
    ),
    1018 => array(
        'dataName' => 'n_seed_b018',
        'image' => '1018',
        'dataType' => '1',
        'level' => '18',
        'unlockLevel' => '36',
        'growValue' => '4320',
    ),
    1019 => array(
        'dataName' => 'n_seed_b019',
        'image' => '1019',
        'dataType' => '1',
        'level' => '19',
        'unlockLevel' => '39',
        'growValue' => '4871',
    ),
    1020 => array(
        'dataName' => 'n_seed_b020',
        'image' => '1020',
        'dataType' => '1',
        'level' => '20',
        'unlockLevel' => '42',
        'growValue' => '5443',
    ),
    1021 => array(
        'dataName' => 'n_seed_b021',
        'image' => '1021',
        'dataType' => '1',
        'level' => '21',
        'unlockLevel' => '45',
        'growValue' => '6037',
    ),
    1022 => array(
        'dataName' => 'n_seed_b022',
        'image' => '1022',
        'dataType' => '1',
        'level' => '22',
        'unlockLevel' => '48',
        'growValue' => '6651',
    ),
    1023 => array(
        'dataName' => 'n_seed_b023',
        'image' => '1023',
        'dataType' => '1',
        'level' => '23',
        'unlockLevel' => '51',
        'growValue' => '7284',
    ),
    1024 => array(
        'dataName' => 'n_seed_b024',
        'image' => '1024',
        'dataType' => '1',
        'level' => '24',
        'unlockLevel' => '54',
        'growValue' => '7936',
    ),
    1025 => array(
        'dataName' => 'n_seed_b025',
        'image' => '1025',
        'dataType' => '1',
        'level' => '25',
        'unlockLevel' => '57',
        'growValue' => '8606',
    ),
    1026 => array(
        'dataName' => 'n_seed_b026',
        'image' => '1026',
        'dataType' => '1',
        'level' => '26',
        'unlockLevel' => '61',
        'growValue' => '9528',
    ),
    1027 => array(
        'dataName' => 'n_seed_b027',
        'image' => '1027',
        'dataType' => '1',
        'level' => '27',
        'unlockLevel' => '65',
        'growValue' => '10480',
    ),
    1028 => array(
        'dataName' => 'n_seed_b028',
        'image' => '1028',
        'dataType' => '1',
        'level' => '28',
        'unlockLevel' => '69',
        'growValue' => '11463',
    ),
    1029 => array(
        'dataName' => 'n_seed_b029',
        'image' => '1029',
        'dataType' => '1',
        'level' => '29',
        'unlockLevel' => '73',
        'growValue' => '12474',
    ),
    1030 => array(
        'dataName' => 'n_seed_b030',
        'image' => '1030',
        'dataType' => '1',
        'level' => '30',
        'unlockLevel' => '77',
        'growValue' => '13513',
    ),
    2001 => array(
        'dataName' => 'n_seed_f001',
        'image' => '2001',
        'dataType' => '2',
        'level' => '1',
        'unlockLevel' => '1',
        'growValue' => '25',
    ),
    2002 => array(
        'dataName' => 'n_seed_f002',
        'image' => '2002',
        'dataType' => '2',
        'level' => '2',
        'unlockLevel' => '1',
        'growValue' => '25',
    ),
    2003 => array(
        'dataName' => 'n_seed_f003',
        'image' => '2003',
        'dataType' => '2',
        'level' => '3',
        'unlockLevel' => '1',
        'growValue' => '25',
    ),
    2004 => array(
        'dataName' => 'n_seed_f004',
        'image' => '2004',
        'dataType' => '2',
        'level' => '4',
        'unlockLevel' => '2',
        'growValue' => '50',
    ),
    2005 => array(
        'dataName' => 'n_seed_f005',
        'image' => '2005',
        'dataType' => '2',
        'level' => '5',
        'unlockLevel' => '5',
        'growValue' => '125',
    ),
    2006 => array(
        'dataName' => 'n_seed_f006',
        'image' => '2006',
        'dataType' => '2',
        'level' => '6',
        'unlockLevel' => '8',
        'growValue' => '200',
    ),
    2007 => array(
        'dataName' => 'n_seed_f007',
        'image' => '2007',
        'dataType' => '2',
        'level' => '7',
        'unlockLevel' => '12',
        'growValue' => '300',
    ),
    2008 => array(
        'dataName' => 'n_seed_f008',
        'image' => '2008',
        'dataType' => '2',
        'level' => '8',
        'unlockLevel' => '16',
        'growValue' => '400',
    ),
    2009 => array(
        'dataName' => 'n_seed_f009',
        'image' => '2009',
        'dataType' => '2',
        'level' => '9',
        'unlockLevel' => '20',
        'growValue' => '500',
    ),
    2010 => array(
        'dataName' => 'n_seed_f010',
        'image' => '2010',
        'dataType' => '2',
        'level' => '10',
        'unlockLevel' => '24',
        'growValue' => '600',
    ),
    2011 => array(
        'dataName' => 'n_seed_f011',
        'image' => '2011',
        'dataType' => '2',
        'level' => '11',
        'unlockLevel' => '28',
        'growValue' => '700',
    ),
    2012 => array(
        'dataName' => 'n_seed_f012',
        'image' => '2012',
        'dataType' => '2',
        'level' => '12',
        'unlockLevel' => '32',
        'growValue' => '800',
    ),
    2013 => array(
        'dataName' => 'n_seed_f013',
        'image' => '2013',
        'dataType' => '2',
        'level' => '13',
        'unlockLevel' => '36',
        'growValue' => '900',
    ),
    2014 => array(
        'dataName' => 'n_seed_f014',
        'image' => '2014',
        'dataType' => '2',
        'level' => '14',
        'unlockLevel' => '40',
        'growValue' => '1000',
    ),
    2015 => array(
        'dataName' => 'n_seed_f015',
        'image' => '2015',
        'dataType' => '2',
        'level' => '15',
        'unlockLevel' => '44',
        'growValue' => '1100',
    ),
    2016 => array(
        'dataName' => 'n_seed_f016',
        'image' => '2016',
        'dataType' => '2',
        'level' => '16',
        'unlockLevel' => '48',
        'growValue' => '1200',
    ),
    2017 => array(
        'dataName' => 'n_seed_f017',
        'image' => '2017',
        'dataType' => '2',
        'level' => '17',
        'unlockLevel' => '52',
        'growValue' => '1300',
    ),
    2018 => array(
        'dataName' => 'n_seed_f018',
        'image' => '2018',
        'dataType' => '2',
        'level' => '18',
        'unlockLevel' => '56',
        'growValue' => '1400',
    ),
    2019 => array(
        'dataName' => 'n_seed_f019',
        'image' => '2019',
        'dataType' => '2',
        'level' => '19',
        'unlockLevel' => '60',
        'growValue' => '1500',
    ),
    2020 => array(
        'dataName' => 'n_seed_f020',
        'image' => '2020',
        'dataType' => '2',
        'level' => '20',
        'unlockLevel' => '64',
        'growValue' => '1600',
    ),
    2021 => array(
        'dataName' => 'n_seed_f021',
        'image' => '2021',
        'dataType' => '2',
        'level' => '21',
        'unlockLevel' => '68',
        'growValue' => '1700',
    ),
    2022 => array(
        'dataName' => 'n_seed_f022',
        'image' => '2022',
        'dataType' => '2',
        'level' => '22',
        'unlockLevel' => '72',
        'growValue' => '1800',
    ),
    2023 => array(
        'dataName' => 'n_seed_f023',
        'image' => '2023',
        'dataType' => '2',
        'level' => '23',
        'unlockLevel' => '76',
        'growValue' => '1900',
    ),
    2024 => array(
        'dataName' => 'n_seed_f024',
        'image' => '2024',
        'dataType' => '2',
        'level' => '24',
        'unlockLevel' => '80',
        'growValue' => '2000',
    ),
    2025 => array(
        'dataName' => 'n_seed_f025',
        'image' => '2025',
        'dataType' => '2',
        'level' => '25',
        'unlockLevel' => '84',
        'growValue' => '2100',
    ),
    2026 => array(
        'dataName' => 'n_seed_f026',
        'image' => '2026',
        'dataType' => '2',
        'level' => '26',
        'unlockLevel' => '101',
        'growValue' => '2175',
    ),
    2027 => array(
        'dataName' => 'n_seed_f027',
        'image' => '2027',
        'dataType' => '2',
        'level' => '27',
        'unlockLevel' => '101',
        'growValue' => '2175',
    ),
    2028 => array(
        'dataName' => 'n_seed_f028',
        'image' => '2028',
        'dataType' => '2',
        'level' => '28',
        'unlockLevel' => '101',
        'growValue' => '2175',
    ),
    2029 => array(
        'dataName' => 'n_seed_f029',
        'image' => '2029',
        'dataType' => '2',
        'level' => '29',
        'unlockLevel' => '101',
        'growValue' => '2175',
    ),
    2030 => array(
        'dataName' => 'n_seed_f030',
        'image' => '2030',
        'dataType' => '2',
        'level' => '30',
        'unlockLevel' => '101',
        'growValue' => '2175',
    ),
    2031 => array(
        'dataName' => 'n_seed_f031',
        'image' => '2031',
        'dataType' => '0',
        'level' => '1',
        'unlockLevel' => '1',
        'growValue' => '0',
    ),
    3001 => array(
        'dataName' => 'n_seed_r001',
        'image' => '3001',
        'dataType' => '3',
        'level' => '1',
        'unlockLevel' => '1',
        'growValue' => '15',
    ),
    3002 => array(
        'dataName' => 'n_seed_r002',
        'image' => '3002',
        'dataType' => '3',
        'level' => '2',
        'unlockLevel' => '1',
        'growValue' => '15',
    ),
    3003 => array(
        'dataName' => 'n_seed_r003',
        'image' => '3003',
        'dataType' => '3',
        'level' => '3',
        'unlockLevel' => '1',
        'growValue' => '15',
    ),
    3004 => array(
        'dataName' => 'n_seed_r004',
        'image' => '3004',
        'dataType' => '3',
        'level' => '4',
        'unlockLevel' => '2',
        'growValue' => '42',
    ),
    3005 => array(
        'dataName' => 'n_seed_r005',
        'image' => '3005',
        'dataType' => '3',
        'level' => '5',
        'unlockLevel' => '4',
        'growValue' => '120',
    ),
    3006 => array(
        'dataName' => 'n_seed_r006',
        'image' => '3006',
        'dataType' => '3',
        'level' => '6',
        'unlockLevel' => '7',
        'growValue' => '277',
    ),
    3007 => array(
        'dataName' => 'n_seed_r007',
        'image' => '3007',
        'dataType' => '3',
        'level' => '7',
        'unlockLevel' => '10',
        'growValue' => '474',
    ),
    3008 => array(
        'dataName' => 'n_seed_r008',
        'image' => '3008',
        'dataType' => '3',
        'level' => '8',
        'unlockLevel' => '13',
        'growValue' => '703',
    ),
    3009 => array(
        'dataName' => 'n_seed_r009',
        'image' => '3009',
        'dataType' => '3',
        'level' => '9',
        'unlockLevel' => '16',
        'growValue' => '960',
    ),
    3010 => array(
        'dataName' => 'n_seed_r010',
        'image' => '3010',
        'dataType' => '3',
        'level' => '10',
        'unlockLevel' => '19',
        'growValue' => '1242',
    ),
    3011 => array(
        'dataName' => 'n_seed_r011',
        'image' => '3011',
        'dataType' => '3',
        'level' => '11',
        'unlockLevel' => '22',
        'growValue' => '1547',
    ),
    3012 => array(
        'dataName' => 'n_seed_r012',
        'image' => '3012',
        'dataType' => '3',
        'level' => '12',
        'unlockLevel' => '25',
        'growValue' => '1875',
    ),
    3013 => array(
        'dataName' => 'n_seed_r013',
        'image' => '3013',
        'dataType' => '3',
        'level' => '13',
        'unlockLevel' => '28',
        'growValue' => '2222',
    ),
    3014 => array(
        'dataName' => 'n_seed_r014',
        'image' => '3014',
        'dataType' => '3',
        'level' => '14',
        'unlockLevel' => '31',
        'growValue' => '2589',
    ),
    3015 => array(
        'dataName' => 'n_seed_r015',
        'image' => '3015',
        'dataType' => '3',
        'level' => '15',
        'unlockLevel' => '34',
        'growValue' => '2973',
    ),
    3016 => array(
        'dataName' => 'n_seed_r016',
        'image' => '3016',
        'dataType' => '3',
        'level' => '16',
        'unlockLevel' => '37',
        'growValue' => '3375',
    ),
    3017 => array(
        'dataName' => 'n_seed_r017',
        'image' => '3017',
        'dataType' => '3',
        'level' => '17',
        'unlockLevel' => '40',
        'growValue' => '3794',
    ),
    3018 => array(
        'dataName' => 'n_seed_r018',
        'image' => '3018',
        'dataType' => '3',
        'level' => '18',
        'unlockLevel' => '43',
        'growValue' => '4229',
    ),
    3019 => array(
        'dataName' => 'n_seed_r019',
        'image' => '3019',
        'dataType' => '3',
        'level' => '19',
        'unlockLevel' => '46',
        'growValue' => '4679',
    ),
    3020 => array(
        'dataName' => 'n_seed_r020',
        'image' => '3020',
        'dataType' => '3',
        'level' => '20',
        'unlockLevel' => '49',
        'growValue' => '5145',
    ),
    3021 => array(
        'dataName' => 'n_seed_r021',
        'image' => '3021',
        'dataType' => '3',
        'level' => '21',
        'unlockLevel' => '52',
        'growValue' => '5624',
    ),
    3022 => array(
        'dataName' => 'n_seed_r022',
        'image' => '3022',
        'dataType' => '3',
        'level' => '22',
        'unlockLevel' => '55',
        'growValue' => '6118',
    ),
    3023 => array(
        'dataName' => 'n_seed_r023',
        'image' => '3023',
        'dataType' => '3',
        'level' => '23',
        'unlockLevel' => '58',
        'growValue' => '6625',
    ),
    3024 => array(
        'dataName' => 'n_seed_r024',
        'image' => '3024',
        'dataType' => '3',
        'level' => '24',
        'unlockLevel' => '62',
        'growValue' => '7322',
    ),
    3025 => array(
        'dataName' => 'n_seed_r025',
        'image' => '3025',
        'dataType' => '3',
        'level' => '25',
        'unlockLevel' => '66',
        'growValue' => '8042',
    ),
    3026 => array(
        'dataName' => 'n_seed_r026',
        'image' => '3026',
        'dataType' => '3',
        'level' => '26',
        'unlockLevel' => '70',
        'growValue' => '8784',
    ),
    3027 => array(
        'dataName' => 'n_seed_r027',
        'image' => '3027',
        'dataType' => '3',
        'level' => '27',
        'unlockLevel' => '74',
        'growValue' => '9548',
    ),
    3028 => array(
        'dataName' => 'n_seed_r028',
        'image' => '3028',
        'dataType' => '3',
        'level' => '28',
        'unlockLevel' => '78',
        'growValue' => '10333',
    ),
    3029 => array(
        'dataName' => 'n_seed_r029',
        'image' => '3029',
        'dataType' => '3',
        'level' => '29',
        'unlockLevel' => '82',
        'growValue' => '11138',
    ),
    3030 => array(
        'dataName' => 'n_seed_r030',
        'image' => '3030',
        'dataType' => '3',
        'level' => '30',
        'unlockLevel' => '86',
        'growValue' => '11962',
    ),
    4001 => array(
        'dataName' => 'n_seed_e001',
        'image' => '4001',
        'dataType' => '4',
        'level' => '1',
        'unlockLevel' => '1',
        'growValue' => '0',
    ),
    4002 => array(
        'dataName' => 'n_seed_e002',
        'image' => '4002',
        'dataType' => '4',
        'level' => '2',
        'unlockLevel' => '1',
        'growValue' => '0',
    ),
    4003 => array(
        'dataName' => 'n_seed_e003',
        'image' => '4003',
        'dataType' => '4',
        'level' => '3',
        'unlockLevel' => '1',
        'growValue' => '0',
    ),
    4004 => array(
        'dataName' => 'n_seed_e004',
        'image' => '4004',
        'dataType' => '4',
        'level' => '4',
        'unlockLevel' => '3',
        'growValue' => '0',
    ),
    4005 => array(
        'dataName' => 'n_seed_e005',
        'image' => '4005',
        'dataType' => '4',
        'level' => '5',
        'unlockLevel' => '5',
        'growValue' => '0',
    ),
    4006 => array(
        'dataName' => 'n_seed_e006',
        'image' => '4006',
        'dataType' => '4',
        'level' => '6',
        'unlockLevel' => '8',
        'growValue' => '0',
    ),
    4007 => array(
        'dataName' => 'n_seed_e007',
        'image' => '4007',
        'dataType' => '4',
        'level' => '7',
        'unlockLevel' => '11',
        'growValue' => '0',
    ),
    4008 => array(
        'dataName' => 'n_seed_e008',
        'image' => '4008',
        'dataType' => '4',
        'level' => '8',
        'unlockLevel' => '14',
        'growValue' => '0',
    ),
    4009 => array(
        'dataName' => 'n_seed_e009',
        'image' => '4009',
        'dataType' => '4',
        'level' => '9',
        'unlockLevel' => '17',
        'growValue' => '0',
    ),
    4010 => array(
        'dataName' => 'n_seed_e010',
        'image' => '4010',
        'dataType' => '4',
        'level' => '10',
        'unlockLevel' => '20',
        'growValue' => '0',
    ),
    4011 => array(
        'dataName' => 'n_seed_e011',
        'image' => '4011',
        'dataType' => '4',
        'level' => '11',
        'unlockLevel' => '23',
        'growValue' => '0',
    ),
    4012 => array(
        'dataName' => 'n_seed_e012',
        'image' => '4012',
        'dataType' => '4',
        'level' => '12',
        'unlockLevel' => '26',
        'growValue' => '0',
    ),
    4013 => array(
        'dataName' => 'n_seed_e013',
        'image' => '4013',
        'dataType' => '4',
        'level' => '13',
        'unlockLevel' => '29',
        'growValue' => '0',
    ),
    4014 => array(
        'dataName' => 'n_seed_e014',
        'image' => '4014',
        'dataType' => '4',
        'level' => '14',
        'unlockLevel' => '32',
        'growValue' => '0',
    ),
    4015 => array(
        'dataName' => 'n_seed_e015',
        'image' => '4015',
        'dataType' => '4',
        'level' => '15',
        'unlockLevel' => '35',
        'growValue' => '0',
    ),
    4016 => array(
        'dataName' => 'n_seed_e016',
        'image' => '4016',
        'dataType' => '4',
        'level' => '16',
        'unlockLevel' => '38',
        'growValue' => '0',
    ),
    4017 => array(
        'dataName' => 'n_seed_e017',
        'image' => '4017',
        'dataType' => '4',
        'level' => '17',
        'unlockLevel' => '41',
        'growValue' => '0',
    ),
    4018 => array(
        'dataName' => 'n_seed_e018',
        'image' => '4018',
        'dataType' => '4',
        'level' => '18',
        'unlockLevel' => '44',
        'growValue' => '0',
    ),
    4019 => array(
        'dataName' => 'n_seed_e019',
        'image' => '4019',
        'dataType' => '4',
        'level' => '19',
        'unlockLevel' => '47',
        'growValue' => '0',
    ),
    4020 => array(
        'dataName' => 'n_seed_e020',
        'image' => '4020',
        'dataType' => '4',
        'level' => '20',
        'unlockLevel' => '50',
        'growValue' => '0',
    ),
    4021 => array(
        'dataName' => 'n_seed_e021',
        'image' => '4021',
        'dataType' => '4',
        'level' => '21',
        'unlockLevel' => '53',
        'growValue' => '0',
    ),
    4022 => array(
        'dataName' => 'n_seed_e023',
        'image' => '4022',
        'dataType' => '4',
        'level' => '22',
        'unlockLevel' => '56',
        'growValue' => '0',
    ),
    4023 => array(
        'dataName' => 'n_seed_e024',
        'image' => '4023',
        'dataType' => '4',
        'level' => '23',
        'unlockLevel' => '59',
        'growValue' => '0',
    ),
    4024 => array(
        'dataName' => 'n_seed_e025',
        'image' => '4024',
        'dataType' => '4',
        'level' => '24',
        'unlockLevel' => '63',
        'growValue' => '0',
    ),
    4025 => array(
        'dataName' => 'n_seed_e026',
        'image' => '4025',
        'dataType' => '4',
        'level' => '25',
        'unlockLevel' => '67',
        'growValue' => '0',
    ),
    4026 => array(
        'dataName' => 'n_seed_e027',
        'image' => '4026',
        'dataType' => '4',
        'level' => '26',
        'unlockLevel' => '71',
        'growValue' => '0',
    ),
    4027 => array(
        'dataName' => 'n_seed_e028',
        'image' => '4027',
        'dataType' => '4',
        'level' => '27',
        'unlockLevel' => '75',
        'growValue' => '0',
    ),
    4028 => array(
        'dataName' => 'n_seed_e022',
        'image' => '4028',
        'dataType' => '4',
        'level' => '28',
        'unlockLevel' => '79',
        'growValue' => '0',
    ),
    4029 => array(
        'dataName' => 'n_seed_e029',
        'image' => '4029',
        'dataType' => '4',
        'level' => '29',
        'unlockLevel' => '83',
        'growValue' => '0',
    ),
    4030 => array(
        'dataName' => 'n_seed_e030',
        'image' => '4030',
        'dataType' => '4',
        'level' => '30',
        'unlockLevel' => '87',
        'growValue' => '0',
    ),

);
?>