<?php

return array(
    39 => array(
        'name' => Yii::t('Item', 'itemName_39'),
        'canBuy' => '0',
        'canSell' => '1',
        'image' => 'n_item_o010.png',
        'category' => '3',
        'level' => '3',
        'description' => Yii::t('Item', 'itemDecription_39'),
        'useLevel' => '0',
        'canUse' => '0',
        'bindRule' => '0',
        'price' => '0',
        'sellPrice' => '1',
        'moneyType' => '0',
        'type' => '8',
        'effect' => array('innerItems' => array(3 => 1, 8 => 1, 13 => 1, 18 => 1,),),
    ),
    40 => array(
        'name' => Yii::t('Item', 'itemName_40'),
        'canBuy' => '0',
        'canSell' => '1',
        'image' => 'n_item_o009.png',
        'category' => '3',
        'level' => '4',
        'description' => Yii::t('Item', 'itemDecription_40'),
        'useLevel' => '0',
        'canUse' => '0',
        'bindRule' => '0',
        'price' => '0',
        'sellPrice' => '2',
        'moneyType' => '0',
        'type' => '8',
        'effect' => array('innerItems' => array(4 => 1, 9 => 1, 14 => 1, 19 => 1, 24 => 1, 29 => 1,),),
    ),
    41 => array(
        'name' => Yii::t('Item', 'itemName_41'),
        'canBuy' => '0',
        'canSell' => '1',
        'image' => 'n_item_o008.png',
        'category' => '3',
        'level' => '5',
        'description' => Yii::t('Item', 'itemDecription_41'),
        'useLevel' => '0',
        'canUse' => '0',
        'bindRule' => '0',
        'price' => '0',
        'sellPrice' => '3',
        'moneyType' => '0',
        'type' => '8',
        'effect' => array('innerItems' => array(5 => 1, 10 => 1, 15 => 1, 20 => 1, 25 => 1, 30 => 1,),),
    ),
    47 => array(
        'name' => Yii::t('Item', 'itemName_47'),
        'canBuy' => '0',
        'canSell' => '0',
        'image' => 'n_item_o010.png',
        'category' => '3',
        'level' => '5',
        'description' => Yii::t('Item', 'itemDecription_47'),
        'useLevel' => '0',
        'canUse' => '1',
        'bindRule' => '0',
        'price' => '0',
        'sellPrice' => '0',
        'moneyType' => '',
        'type' => '8',
        'effect' => 0,
    ),
);
?>