<?php
return array(
    4001 => array(
        'attributes' => array(
            1 => 4 ,
            2 => 3 ,
            3 => 2 ,
            4 => 1 ,
            5 => 0 ,
            6 => 0 ,
        ) ,
        'position' => 0 ,
    ) ,
    4002 => array(
        'attributes' => array(
            1 => 3 ,
            2 => 4 ,
            3 => 1 ,
            4 => 2 ,
            5 => 0 ,
            6 => 0 ,
        ) ,
        'position' => 0 ,
    ) ,
    4003 => array(
        'attributes' => array(
            1 => 2 ,
            2 => 1 ,
            3 => 4 ,
            4 => 3 ,
            5 => 0 ,
            6 => 0 ,
        ) ,
        'position' => 0 ,
    ) ,
    4004 => array(
        'attributes' => array(
            1 => 1 ,
            2 => 2 ,
            3 => 3 ,
            4 => 4 ,
            5 => 0 ,
            6 => 0 ,
        ) ,
        'position' => 0 ,
    ) ,
    4005 => array(
        'attributes' => array(
            1 => 4 ,
            2 => 2 ,
            3 => 1 ,
            4 => 3 ,
            5 => 0 ,
            6 => 0 ,
        ) ,
        'position' => 0 ,
    ) ,
    4006 => array(
        'attributes' => array(
            1 => 1 ,
            2 => 4 ,
            3 => 3 ,
            4 => 2 ,
            5 => 0 ,
            6 => 0 ,
        ) ,
        'position' => 0 ,
    ) ,
    4007 => array(
        'attributes' => array(
            1 => 1 ,
            2 => 3 ,
            3 => 4 ,
            4 => 2 ,
            5 => 0 ,
            6 => 0 ,
        ) ,
        'position' => 0 ,
    ) ,
    4008 => array(
        'attributes' => array(
            1 => 3 ,
            2 => 2 ,
            3 => 1 ,
            4 => 4 ,
            5 => 0 ,
            6 => 0 ,
        ) ,
        'position' => 0 ,
    ) ,
    4009 => array(
        'attributes' => array(
            1 => 4 ,
            2 => 1 ,
            3 => 2 ,
            4 => 3 ,
            5 => 0 ,
            6 => 0 ,
        ) ,
        'position' => 0 ,
    ) ,
    4010 => array(
        'attributes' => array(
            1 => 3 ,
            2 => 4 ,
            3 => 2 ,
            4 => 1 ,
            5 => 0 ,
            6 => 0 ,
        ) ,
        'position' => 0 ,
    ) ,
    4011 => array(
        'attributes' => array(
            1 => 2 ,
            2 => 3 ,
            3 => 4 ,
            4 => 1 ,
            5 => 0 ,
            6 => 0 ,
        ) ,
        'position' => 0 ,
    ) ,
    4012 => array(
        'attributes' => array(
            1 => 2 ,
            2 => 1 ,
            3 => 3 ,
            4 => 4 ,
            5 => 0 ,
            6 => 0 ,
        ) ,
        'position' => 0 ,
    ) ,
    4013 => array(
        'attributes' => array(
            1 => 4 ,
            2 => 2 ,
            3 => 0 ,
            4 => 3 ,
            5 => 1 ,
            6 => 0 ,
        ) ,
        'position' => 0 ,
    ) ,
    4014 => array(
        'attributes' => array(
            1 => 2 ,
            2 => 4 ,
            3 => 3 ,
            4 => 0 ,
            5 => 1 ,
            6 => 0 ,
        ) ,
        'position' => 0 ,
    ) ,
    4015 => array(
        'attributes' => array(
            1 => 0 ,
            2 => 3 ,
            3 => 4 ,
            4 => 2 ,
            5 => 1 ,
            6 => 0 ,
        ) ,
        'position' => 0 ,
    ) ,
    4016 => array(
        'attributes' => array(
            1 => 3 ,
            2 => 0 ,
            3 => 2 ,
            4 => 4 ,
            5 => 1 ,
            6 => 0 ,
        ) ,
        'position' => 0 ,
    ) ,
    4017 => array(
        'attributes' => array(
            1 => 1 ,
            2 => 0 ,
            3 => 2 ,
            4 => 0 ,
            5 => 4 ,
            6 => 3 ,
        ) ,
        'position' => 1 ,
    ) ,
    4018 => array(
        'attributes' => array(
            1 => 3 ,
            2 => 1 ,
            3 => 2 ,
            4 => 0 ,
            5 => 4 ,
            6 => 0 ,
        ) ,
        'position' => 1 ,
    ) ,
    4019 => array(
        'attributes' => array(
            1 => 1 ,
            2 => 3 ,
            3 => 0 ,
            4 => 2 ,
            5 => 0 ,
            6 => 4 ,
        ) ,
        'position' => 1 ,
    ) ,
    4020 => array(
        'attributes' => array(
            1 => 0 ,
            2 => 0 ,
            3 => 1 ,
            4 => 3 ,
            5 => 4 ,
            6 => 2 ,
        ) ,
        'position' => 1 ,
    ) ,
    4021 => array(
        'attributes' => array(
            1 => 2 ,
            2 => 1 ,
            3 => 0 ,
            4 => 0 ,
            5 => 3 ,
            6 => 4 ,
        ) ,
        'position' => 1 ,
    ) ,
    4022 => array(
        'attributes' => array(
            1 => 0 ,
            2 => 2 ,
            3 => 0 ,
            4 => 1 ,
            5 => 4 ,
            6 => 3 ,
        ) ,
        'position' => 1 ,
    ) ,
    4023 => array(
        'attributes' => array(
            1 => 3 ,
            2 => 0 ,
            3 => 1 ,
            4 => 2 ,
            5 => 0 ,
            6 => 4 ,
        ) ,
        'position' => 1 ,
    ) ,
    4024 => array(
        'attributes' => array(
            1 => 0 ,
            2 => 3 ,
            3 => 0 ,
            4 => 1 ,
            5 => 2 ,
            6 => 4 ,
        ) ,
        'position' => 1 ,
    ) ,
    4025 => array(
        'attributes' => array(
            1 => 4 ,
            2 => 2 ,
            3 => 3 ,
            4 => 0 ,
            5 => 0 ,
            6 => 1 ,
        ) ,
        'position' => 1 ,
    ) ,
    4026 => array(
        'attributes' => array(
            1 => 0 ,
            2 => 4 ,
            3 => 3 ,
            4 => 2 ,
            5 => 0 ,
            6 => 1 ,
        ) ,
        'position' => 0 ,
    ) ,
    4027 => array(
        'attributes' => array(
            1 => 0 ,
            2 => 0 ,
            3 => 4 ,
            4 => 2 ,
            5 => 3 ,
            6 => 1 ,
        ) ,
        'position' => 1 ,
    ) ,
    4028 => array(
        'attributes' => array(
            1 => 3 ,
            2 => 0 ,
            3 => 0 ,
            4 => 4 ,
            5 => 2 ,
            6 => 1 ,
        ) ,
        'position' => 1 ,
    ) ,
    4029 => array(
        'attributes' => array(
            1 => 2 ,
            2 => 3 ,
            3 => 0 ,
            4 => 0 ,
            5 => 4 ,
            6 => 1 ,
        ) ,
        'position' => 1 ,
    ) ,
    4030 => array(
        'attributes' => array(
            1 => 0 ,
            2 => 0 ,
            3 => 3 ,
            4 => 2 ,
            5 => 1 ,
            6 => 4 ,
        ) ,
        'position' => 1 ,
    ) ,

);
