<?php

return array(
    31 => array(
        'name' => Yii::t('Item', 'itemName_31'),
        'canBuy' => '1',
        'canSell' => '1',
        'image' => 'n_item_o001.png',
        'category' => '0',
        'level' => '3',
        'description' => Yii::t('Item', 'itemDecription_31'),
        'useLevel' => '0',
        'canUse' => '0',
        'bindRule' => '0',
        'price' => '150',
        'sellPrice' => '60',
        'moneyType' => '1',
        'type' => '7',
        'effect' => array('growValue' => 500,),
    ),
    32 => array(
        'name' => Yii::t('Item', 'itemName_32'),
        'canBuy' => '1',
        'canSell' => '1',
        'image' => 'n_item_o002.png',
        'category' => '0',
        'level' => '4',
        'description' => Yii::t('Item', 'itemDecription_32'),
        'useLevel' => '0',
        'canUse' => '0',
        'bindRule' => '0',
        'price' => '300',
        'sellPrice' => '120',
        'moneyType' => '1',
        'type' => '7',
        'effect' => array('growValue' => 1000,),
    ),
    33 => array(
        'name' => Yii::t('Item', 'itemName_33'),
        'canBuy' => '1',
        'canSell' => '1',
        'image' => 'n_item_o004.png',
        'category' => '0',
        'level' => '5',
        'description' => Yii::t('Item', 'itemDecription_33'),
        'useLevel' => '0',
        'canUse' => '0',
        'bindRule' => '0',
        'price' => '600',
        'sellPrice' => '240',
        'moneyType' => '1',
        'type' => '7',
        'effect' => array('growValue' => 2000,),
    ),
    34 => array(
        'name' => Yii::t('Item', 'itemName_34'),
        'canBuy' => '1',
        'canSell' => '1',
        'image' => 'n_item_o003.png',
        'category' => '0',
        'level' => '4',
        'description' => Yii::t('Item', 'itemDecription_34'),
        'useLevel' => '0',
        'canUse' => '0',
        'bindRule' => '0',
        'price' => '500',
        'sellPrice' => '200',
        'moneyType' => '1',
        'type' => '9',
        'effect' => array('reduceTime' => 4,),
    ),
    35 => array(
        'name' => Yii::t('Item', 'itemName_35'),
        'canBuy' => '1',
        'canSell' => '1',
        'image' => 'n_item_o013.png',
        'category' => '0',
        'level' => '5',
        'description' => Yii::t('Item', 'itemDecription_35'),
        'useLevel' => '0',
        'canUse' => '0',
        'bindRule' => '0',
        'price' => '650',
        'sellPrice' => '260',
        'moneyType' => '1',
        'type' => '9',
        'effect' => array('reduceTime' => 0,),
    ),
    36 => array(
        'name' => Yii::t('Item', 'itemName_36'),
        'canBuy' => '0',
        'canSell' => '1',
        'image' => 'n_item_o005.png',
        'category' => '0',
        'level' => '5',
        'description' => Yii::t('Item', 'itemDecription_36'),
        'useLevel' => '0',
        'canUse' => '0',
        'bindRule' => '0',
        'price' => '0',
        'sellPrice' => '0',
        'moneyType' => '',
        'type' => '9',
        'effect' => array('reduceTime' => 0,),
    ),
    37 => array(
        'name' => Yii::t('Item', 'itemName_37'),
        'canBuy' => '1',
        'canSell' => '1',
        'image' => 'n_item_o014.png',
        'category' => '0',
        'level' => '5',
        'description' => Yii::t('Item', 'itemDecription_37'),
        'useLevel' => '0',
        'canUse' => '0',
        'bindRule' => '0',
        'price' => '1000',
        'sellPrice' => '400',
        'moneyType' => '1',
        'type' => '9',
        'effect' => array('actionPoint' => 0.5,),
    ),
    38 => array(
        'name' => Yii::t('Item', 'itemName_38'),
        'canBuy' => '1',
        'canSell' => '1',
        'image' => 'n_item_o007.png',
        'category' => '0',
        'level' => '5',
        'description' => Yii::t('Item', 'itemDecription_38'),
        'useLevel' => '0',
        'canUse' => '0',
        'bindRule' => '0',
        'price' => '2000',
        'sellPrice' => '800',
        'moneyType' => '1',
        'type' => '9',
        'effect' => array('actionPoint' => 1,),
    ),
    39 => array(
        'name' => Yii::t('Item', 'itemName_39'),
        'canBuy' => '0',
        'canSell' => '1',
        'image' => 'n_item_o010.png',
        'category' => '3',
        'level' => '3',
        'description' => Yii::t('Item', 'itemDecription_39'),
        'useLevel' => '0',
        'canUse' => '0',
        'bindRule' => '0',
        'price' => '0',
        'sellPrice' => '1',
        'moneyType' => '0',
        'type' => '8',
        'effect' => array('innerItems' => array(3 => 1, 8 => 1, 13 => 1, 18 => 1,),),
    ),
    40 => array(
        'name' => Yii::t('Item', 'itemName_40'),
        'canBuy' => '0',
        'canSell' => '1',
        'image' => 'n_item_o009.png',
        'category' => '3',
        'level' => '4',
        'description' => Yii::t('Item', 'itemDecription_40'),
        'useLevel' => '0',
        'canUse' => '0',
        'bindRule' => '0',
        'price' => '0',
        'sellPrice' => '2',
        'moneyType' => '0',
        'type' => '8',
        'effect' => array('innerItems' => array(4 => 1, 9 => 1, 14 => 1, 19 => 1, 24 => 1, 29 => 1,),),
    ),
    41 => array(
        'name' => Yii::t('Item', 'itemName_41'),
        'canBuy' => '0',
        'canSell' => '1',
        'image' => 'n_item_o008.png',
        'category' => '3',
        'level' => '5',
        'description' => Yii::t('Item', 'itemDecription_41'),
        'useLevel' => '0',
        'canUse' => '0',
        'bindRule' => '0',
        'price' => '0',
        'sellPrice' => '3',
        'moneyType' => '0',
        'type' => '8',
        'effect' => array('innerItems' => array(5 => 1, 10 => 1, 15 => 1, 20 => 1, 25 => 1, 30 => 1,),),
    ),
    43 => array(
        'name' => Yii::t('Item', 'itemName_43'),
        'canBuy' => '1',
        'canSell' => '0',
        'image' => 'n_item_o015.png',
        'category' => '6',
        'level' => '5',
        'description' => Yii::t('Item', 'itemDecription_43'),
        'useLevel' => '0',
        'canUse' => '1',
        'bindRule' => '0',
        'price' => '200',
        'sellPrice' => '0',
        'moneyType' => '1',
        'type' => '10',
        'effect' => array('gold' => 1000,),
    ),
    44 => array(
        'name' => Yii::t('Item', 'itemName_44'),
        'canBuy' => '1',
        'canSell' => '0',
        'image' => 'n_item_o016.png',
        'category' => '6',
        'level' => '5',
        'description' => Yii::t('Item', 'itemDecription_44'),
        'useLevel' => '0',
        'canUse' => '1',
        'bindRule' => '0',
        'price' => '950',
        'sellPrice' => '0',
        'moneyType' => '1',
        'type' => '10',
        'effect' => array('gold' => 5000,),
    ),
    45 => array(
        'name' => Yii::t('Item', 'itemName_45'),
        'canBuy' => '1',
        'canSell' => '0',
        'image' => 'n_item_o017.png',
        'category' => '6',
        'level' => '5',
        'description' => Yii::t('Item', 'itemDecription_45'),
        'useLevel' => '0',
        'canUse' => '1',
        'bindRule' => '0',
        'price' => '1800',
        'sellPrice' => '0',
        'moneyType' => '1',
        'type' => '10',
        'effect' => array('gold' => 10000,),
    ),
    46 => array(
        'name' => Yii::t('Item', 'itemName_46'),
        'canBuy' => '1',
        'canSell' => '0',
        'image' => 'n_item_o018.png',
        'category' => '6',
        'level' => '5',
        'description' => Yii::t('Item', 'itemDecription_46'),
        'useLevel' => '0',
        'canUse' => '1',
        'bindRule' => '0',
        'price' => '17000',
        'sellPrice' => '0',
        'moneyType' => '1',
        'type' => '10',
        'effect' => array('gold' => 100000,),
    ),
    47 => array(
        'name' => Yii::t('Item', 'itemName_47'),
        'canBuy' => '0',
        'canSell' => '0',
        'image' => 'n_item_o010.png',
        'category' => '3',
        'level' => '5',
        'description' => Yii::t('Item', 'itemDecription_47'),
        'useLevel' => '0',
        'canUse' => '1',
        'bindRule' => '0',
        'price' => '0',
        'sellPrice' => '0',
        'moneyType' => '',
        'type' => '8',
        'effect' => 0,
    ),
    14001 => array(
        'name' => '14001宝箱',
        'description' => '14001宝箱',
        'category' => '-1',
        'moneyType' => '0',
        'type' => '8',
        'level' => '',
        'price' => '0',
        'sellPrice' => '',
        'image' => 'n_garden_d096.png',
        'canBuy' => '0',
        'canSell' => '1',
        'effect' => array(
            'innerItems' => array(
                31 => 5,
            ),
        )
    ),
    14002 => array(
        'name' => '14002宝箱',
        'description' => '14002宝箱',
        'category' => '-1',
        'moneyType' => '0',
        'type' => '8',
        'level' => '',
        'price' => '0',
        'sellPrice' => '',
        'image' => 'n_garden_d096.png',
        'canBuy' => '0',
        'canSell' => '1',
        'effect' => array(
            'innerItems' => array(
                34 => 5,
            ),
        )
    ),
    14003 => array(
        'name' => '14003宝箱',
        'description' => '14003宝箱',
        'category' => '-1',
        'moneyType' => '0',
        'type' => '8',
        'level' => '',
        'price' => '0',
        'sellPrice' => '',
        'image' => 'n_garden_d096.png',
        'canBuy' => '0',
        'canSell' => '1',
        'effect' => array(
            'innerItems' => array(
                39 => 1,
            ),
        )
    ),
    14004 => array(
        'name' => '14004宝箱',
        'description' => '14004宝箱',
        'category' => '-1',
        'moneyType' => '0',
        'type' => '8',
        'level' => '',
        'price' => '0',
        'sellPrice' => '',
        'image' => 'n_garden_d096.png',
        'canBuy' => '0',
        'canSell' => '1',
        'effect' => array(
            'innerItems' => array(
                40 => 1,
            ),
        )
    ),
    14005 => array(
        'name' => '14005宝箱',
        'description' => '14005宝箱',
        'category' => '-1',
        'moneyType' => '0',
        'type' => '8',
        'level' => '',
        'price' => '0',
        'sellPrice' => '',
        'image' => 'n_garden_d096.png',
        'canBuy' => '0',
        'canSell' => '1',
        'effect' => array(
            'innerItems' => array(
                38 => 1,
            ),
        )
    ),
    14006 => array(
        'name' => '14006宝箱',
        'description' => '14006宝箱',
        'category' => '-1',
        'moneyType' => '0',
        'type' => '8',
        'level' => '',
        'price' => '0',
        'sellPrice' => '',
        'image' => 'n_garden_d096.png',
        'canBuy' => '0',
        'canSell' => '1',
        'effect' => array(
            'innerItems' => array(
                41 => 2,
            ),
        )
    ),
    14007 => array(
        'name' => '14007宝箱',
        'description' => '14007宝箱',
        'category' => '-1',
        'moneyType' => '0',
        'type' => '8',
        'level' => '',
        'price' => '0',
        'sellPrice' => '',
        'image' => 'n_garden_d096.png',
        'canBuy' => '0',
        'canSell' => '1',
        'effect' => array(
            'innerItems' => array(
                38 => 3,
            ),
        )
    ),
);
?>